# -*- coding: utf-8 -*-
"""All site copy and structured content. No em dashes anywhere."""

NAV = [
    {"id": "residential", "label": "Residential", "href": "residential.html"},
    {"id": "commercial", "label": "Commercial", "href": "commercial.html"},
    {"id": "services", "label": "Services", "href": "services.html"},
    {"id": "about", "label": "About", "href": "about.html"},
    {"id": "blog", "label": "Journal", "href": "blog.html"},
]

PARTNERS = ["Control4", "Honeywell", "Resideo", "Alarm.com", "Sonos", "Denon HEOS", "Triad", "Niles",
            "Yale", "Schlage", "Kwikset", "Hikvision", "TruVision", "TruPortal", "Panasonic",
            "Epson", "Sony", "Samsung", "LG", "Marantz", "Polk Audio", "MartinLogan", "Ecobee", "Vanderbilt"]

# ---------------------------------------------------------------- HOME
SWITCH = [
    {"word": "Security", "img": "dusk-black", "title": "Security & fire",
     "text": "Monitored burglary, smoke, heat, carbon monoxide and flood detection, designed around a survey of your property.",
     "spec": [("Detection", "Door, window, glass, motion"), ("Signal", "Cellular, tested daily"), ("Control", "Phone, keypad, touchscreen")],
     "href": "residential.html#security"},
    {"word": "Surveillance", "img": "cameras", "title": "Surveillance",
     "text": "Hardwired IP cameras recording to a local NVR, with live view and playback on your phone from anywhere.",
     "spec": [("Resolution", "2 MP to 4K"), ("Night vision", "Infrared, 30 to 50 m"), ("Recording", "NVR or server")],
     "href": "commercial.html#services"},
    {"word": "Access", "img": "smart-lock", "title": "Access control",
     "text": "Smart locks at home. Card, fob and app access at work, with a log of every door and every person.",
     "spec": [("Home", "Yale, Schlage, Kwikset"), ("Business", "1 to 64 doors"), ("Reports", "By door, person or time")],
     "href": "commercial.html#services"},
    {"word": "Automation", "img": "interior-fire", "title": "Home automation",
     "text": "One Control4 system for lighting, climate, shades, audio, video and security, run from a keypad, a screen or your phone.",
     "spec": [("Platform", "Control4"), ("Scenes", "One press, many actions"), ("Control", "App, keypad, voice, TV")],
     "href": "residential.html#automation"},
    {"word": "Lighting", "img": "pendants", "title": "Lighting & shades",
     "text": "Scenes in place of switch banks, landscape lighting that follows sunset all year, and motorized shades on a schedule.",
     "spec": [("Keypads", "Seven-button, programmable"), ("Exterior", "Astronomical clock"), ("Shades", "Motorized, scheduled")],
     "href": "residential.html#lighting"},
    {"word": "Audio", "img": "living-wood", "title": "Multi-room audio",
     "text": "Music in every room and out on the deck, from speakers that disappear into walls, ceilings and landscaping.",
     "spec": [("Speakers", "In-wall, in-ceiling, outdoor"), ("Streaming", "Spotify, SiriusXM, Pandora"), ("Zones", "Together or separate")],
     "href": "residential.html#audio"},
    {"word": "Theater", "img": "projector", "title": "Home theater",
     "text": "Dedicated theaters and everyday media rooms, designed for the space, with the equipment kept out of sight.",
     "spec": [("Display", "Projector or 80 to 90 in panel"), ("Sound", "Surround, soundbar, subwoofer"), ("Control", "One button on")],
     "href": "residential.html#theater"},
]

SCENES = [
    {"name": "Arrive home", "time": "17:40", "veil": ".12", "shade": "0",
     "lights": "70%", "shades": "Open", "security": "Disarmed", "audio": "Kitchen",
     "text": "Garage opens, alarm disarms, entry lights rise and music starts in the kitchen."},
    {"name": "Movie night", "time": "20:30", "veil": ".5", "shade": "94",
     "lights": "8%", "shades": "Closed", "security": "Stay", "audio": "Theater",
     "text": "Lights dim, shades close, the projector and surround sound come on."},
    {"name": "Goodnight", "time": "23:00", "veil": ".78", "shade": "94",
     "lights": "Off", "shades": "Closed", "security": "Night", "audio": "Off",
     "text": "Every light off, doors locked, alarm armed, thermostat set back two degrees."},
    {"name": "Away", "time": "08:10", "veil": ".3", "shade": "48",
     "lights": "Pattern", "shades": "Half", "security": "Away", "audio": "Off",
     "text": "Alarm armed, locks checked, lights follow a lived-in pattern, cameras alert your phone."},
]

CAPS = [
    {"img": "cameras", "alt": "Rows of white security cameras mounted on a dark wall", "wide": True, "tag": "Surveillance",
     "title": "Hardwired camera systems", "text": "Network cable to every camera, recording to a local NVR. Constant video, no Wi-Fi dropouts."},
    {"img": "smart-lock", "alt": "A hand holding a phone beside a smart lock on a door", "tag": "Access",
     "title": "Remote entry", "text": "Let a contractor in from three states away, then lock the door behind them."},
    {"img": "pendants", "alt": "Kitchen pendant lights over a marble island", "tag": "Lighting",
     "title": "Scenes, not switches", "text": "One seven-button keypad replaces a wall of switches and sets the room in a press."},
    {"img": "projector", "alt": "A projector beam cutting through a dark room", "tag": "Theater",
     "title": "Dedicated home theaters", "text": "Projector or large-format panel, surround sound, and the equipment rack hidden in a closet."},
    {"img": "bedroom-glass", "alt": "A bedroom with floor-to-ceiling glass and soft daylight", "wide": True, "tag": "Shades",
     "title": "Motorized shading", "text": "Shades that close for movie night, follow sunrise and keep the sun off floors and furniture."},
    {"img": "rack", "alt": "Network patch cables plugged into a rack-mounted switch", "tag": "Infrastructure",
     "title": "Structured wiring", "text": "Clean racks, labeled runs and access points placed where coverage actually needs them."},
    {"img": "conference", "alt": "A long conference table and chairs beside a glass wall", "tag": "Commercial AV",
     "title": "Conference and training rooms", "text": "Display, microphones and in-ceiling speakers, set up so anyone can walk in and present."},
    {"img": "restaurant", "alt": "A dark, warmly lit restaurant dining room", "tag": "Hospitality",
     "title": "Restaurant and bar systems", "text": "Background music, paging and screens for game day, each zoned by area."},
]

NOTES = [
    {"where": "Pittstown, NJ", "what": "Carbon monoxide · 1:00\u00a0AM", "title": "A CO sensor trips in the middle of the night.",
     "text": "Our monitoring station reaches the homeowner while the Quakertown Fire Company is dispatched. Firefighters measure carbon monoxide at life-threatening levels.",
     "out": "Family safe"},
    {"where": "Somerville, NJ", "what": "Smoke · Mixed use", "title": "Smoke in an apartment above a dental office.",
     "text": "The fire department finds a fire inside a recessed light in a newly renovated bathroom, caught early enough to prevent serious damage.",
     "out": "Contained early"},
    {"where": "Residence", "what": "Entry chime · 5:00\u00a0AM", "title": "A door chime ends a break-in.",
     "text": "With the alarm off, chime mode sounds as a basement door opens and the intruder leaves. Police later confirm several neighboring homes were burglarized that morning.",
     "out": "Nothing taken"},
    {"where": "Residence", "what": "Fire · December", "title": "A candle left burning on a piano.",
     "text": "Hours after a family leaves for the holidays, the smoke sensor reports a fire in the music room. Early detection means smoke damage instead of a lost home.",
     "out": "Losses minimized"},
]

# ---------------------------------------------------------------- RESIDENTIAL
RES = [
    {"id": "security", "short": "Security", "cat": "Security", "title": "Security &amp; Surveillance", "img": "dusk-black",
     "alt": "A dark timber house at twilight with warm light in every window",
     "text": "Monitored burglary, fire, carbon monoxide and flood protection, with cameras placed from a survey of your property. We install and service thousands of systems across New Jersey and Pennsylvania.",
     "specs": ["Honeywell / Resideo", "Alarm.com", "Cellular radio", "2 MP to 4K"],
     "ticks": ["Smoke, heat, CO, glass break, motion, door, window, temperature and flood sensors",
               "Hardwired, wireless or a mix, chosen room by room",
               "Cellular communication, more reliable than phone or internet lines",
               "Battery backup in the panel for power outages",
               "Hardwired IP cameras to a local NVR, or Wi-Fi cameras where wiring is impractical",
               "Doorbell cameras with instant alerts and two-way talk"],
     "note": "Placement matters. A smoke sensor within three feet of a supply duct collects dust and trips false alarms. Details like this are why we install every system ourselves."},
    {"id": "locks", "short": "Smart locks", "cat": "Access", "title": "Smart Locks &amp; Access", "img": "smart-lock",
     "alt": "A hand holding a phone with a lock app beside a smart lock",
     "text": "Lock, unlock and check every door from your phone. Let in a contractor while you are away, and know the moment the kids are home from school.",
     "specs": ["Yale", "Schlage", "Kwikset", "August", "Z-Wave / Zigbee"],
     "ticks": ["Deadbolt and lever styles in finishes to match your hardware",
               "Keypad codes for family, guests and service companies",
               "A notification for every lock and unlock",
               "Garage door status and control in the same app",
               "Backup battery terminal if the lock's batteries run out"],
     "note": "Remote control relies on your internet connection. The keypad at the door works either way."},
    {"id": "automation", "short": "Automation", "cat": "Automation", "title": "Home Automation", "img": "interior-fire",
     "alt": "A bright living room with arched windows and a fireplace",
     "text": "Control4 ties lighting, climate, shades, audio, video and security into one system, run from keypads, touchscreens, your phone or your voice. It is the smart home platform we recommend and support.",
     "specs": ["Control4", "Ecobee", "Honeywell", "Nest"],
     "ticks": ["Smart thermostats with schedules and remote adjustment",
               "Automatic setback at night and back to comfort by morning",
               "On-screen control of climate and security from any TV",
               "Scenes that combine lights, shades, music and locks",
               "Expandable as your needs change"],
     "note": "Check with your HVAC contractor first: some systems, including certain Carrier units, need an extra module to work with a smart thermostat."},
    {"id": "lighting", "short": "Lighting & shades", "cat": "Lighting", "title": "Lighting &amp; Shade Control", "img": "pendants",
     "alt": "Pendant lights hanging over a kitchen island",
     "text": "Lighting scenes at the press of a button, exterior lights that follow sunset through the seasons, and motorized shades that protect floors and furniture from the sun.",
     "specs": ["Seven-button keypads", "Astronomical clock", "Motorized shades"],
     "ticks": ["Keypads that replace banks of switches, each button a scene",
               "All lights off from any room, or from your phone",
               "Landscape lighting that adjusts to sunrise and sunset automatically",
               "Shades that open and close on schedule or with a scene",
               "Movie night: lights dim, shades drop, the screen comes on"],
     "note": None},
    {"id": "theater", "short": "Home theater", "cat": "Theater", "title": "Home Theater", "img": "projector",
     "alt": "A projector beam crossing a dark room",
     "text": "Dedicated theaters and everyday family rooms, designed for the space and the budget, with the equipment housed out of sight. Home theater installation across New Jersey, with upgrades as technology moves on.",
     "specs": ["Sony", "Samsung", "LG", "Epson", "Denon", "Triad", "MartinLogan"],
     "ticks": ["Projector and screen, or an 80 to 90 inch panel with less upkeep",
               "Surround receivers with visible or hidden speakers",
               "Soundbars with wireless rears and subwoofers from Sonos, Denon HEOS, Bose and Polk",
               "Equipment located remotely, out of the living space",
               "One-button startup for the whole system"],
     "note": "Large panels now cost less to own than most projectors, with no bulbs to replace. We will tell you which suits your room."},
    {"id": "audio", "short": "Audio", "cat": "Audio", "title": "Multi-Room Audio", "img": "living-wood",
     "alt": "A living room with timber wall, sofa and open plan kitchen",
     "text": "Music in every room and out on the deck, controlled from your phone. The same song everywhere, or something different in each zone.",
     "specs": ["Sonos", "Denon HEOS", "Triad", "Niles", "Marantz"],
     "ticks": ["In-wall and in-ceiling speakers with paintable grilles",
               "Amplifiers installed out of view in the basement or utility room",
               "Weatherproof outdoor speakers, including rock and planter designs",
               "Spotify, Pandora, SiriusXM, iHeartRadio and your own library",
               "Control from a phone, tablet, keypad or touchscreen"],
     "note": None},
    {"id": "control", "short": "Integrated control", "cat": "Control", "title": "Integrated Control", "img": "living-tv",
     "alt": "A living room with a wall-mounted TV and media shelving",
     "text": "One interface for the whole house. Arm the alarm from the TV, see cameras on any screen and run the home from a single app, wherever you are.",
     "specs": ["Control4", "Alarm.com", "Touchscreens"],
     "ticks": ["Virtual security keypad on any TV",
               "Camera feeds on TVs, touchscreens and phones",
               "Garage door sensors that report open or closed",
               "Alerts for leaks, power loss and power restored",
               "Real-time alerts and remote access from anywhere"],
     "note": None},
    {"id": "consulting", "short": "Consulting", "cat": "Consulting", "title": "Security &amp; Control Consulting", "img": "blueprint",
     "alt": "A designer drafting a floor plan by hand",
     "text": "Building, renovating, or living with a system you did not choose? We assess what you have, what you need and what is worth keeping, then give you a clear plan.",
     "specs": ["Site survey", "Existing systems", "New construction"],
     "ticks": ["A walk-through with you, your builder or your architect",
               "Review of existing equipment across most major brands",
               "Wiring plans for new construction and renovation",
               "Priorities, options and costs set out plainly",
               "Coordination with electricians and HVAC contractors"],
     "note": None},
]

DAY = [
    {"time": "06:30", "img": "bedroom-glass", "title": "Shades rise",
     "text": "Bedroom shades open slowly at sunrise and the thermostat returns to its daytime setpoint."},
    {"time": "08:10", "img": "white-house", "title": "Away",
     "text": "One button by the door arms the alarm, checks every lock and turns off every light."},
    {"time": "15:20", "img": "smart-lock", "title": "Home from school",
     "text": "A keypad code opens the front door and your phone shows who is home."},
    {"time": "17:45", "img": "dusk-timber", "title": "Dusk",
     "text": "Landscape lighting comes on by astronomical clock. No timers to reset when the season changes."},
    {"time": "20:30", "img": "projector", "title": "Movie night",
     "text": "Lights dim, shades close, the projector warms up and the surround sound comes on."},
    {"time": "23:00", "img": "dusk-black", "title": "Goodnight",
     "text": "Lights off, doors locked, alarm set to night mode. The cameras keep watch."},
]

RES_FAQ = [
    {"q": "Is the router from my internet provider good enough for smart devices?",
     "a": "Often not for a whole house. Provider routers are built for convenience, and coverage usually fades at the edges of a home. Locks, cameras and speakers need a strong, steady signal, so we typically recommend a current router with wired access points placed where they are needed."},
    {"q": "Does a security system really make me safer?",
     "a": "A properly installed, monitored system detects fire, carbon monoxide and intrusion, and gets help moving while you are asleep or away. Placement and monitoring are what make the difference, which is why we design and install every system ourselves."},
    {"q": "Do I need a landline for an alarm system?",
     "a": "No. Our systems communicate by cellular radio, which is more reliable than internet phone service and does not depend on copper lines, which are being phased out in many areas."},
    {"q": "I have an older home. Can I still get a reliable system?",
     "a": "Yes. We use hardwired devices where walls are accessible and wireless sensors where they are not, so an older home can be protected without opening up finished walls."},
    {"q": "What do I need for a true 4K viewing experience?",
     "a": "A 4K display, 4K sources such as a streaming device or player, a fast and stable internet connection, and HDMI cabling rated for the signal. We check every link in that chain when we design a room."},
]

# ---------------------------------------------------------------- COMMERCIAL
COM = [
    {"id": "security-fire", "anchor": "services", "cat": "Security", "title": "Security &amp; Fire", "img": "office-dark",
     "alt": "An office floor at night lit by monitors and pendant lights",
     "text": "Burglary and fire panels sized to the building and ready to grow. Addressable devices tell the monitoring station exactly which room or sensor is in alarm.",
     "cols": [{"h": "Detection", "items": ["Motion, glass break and door switches", "Smoke, heat and HVAC duct smoke sensors", "Manual pull stations and wireless panic buttons", "Carbon monoxide and temperature alerts", "Sprinkler flow, tamper and kitchen hood suppression monitoring"]},
              {"h": "Built in", "items": ["Horns and strobes for evacuation", "Addressable zones with names and locations", "Auto-recharging battery backup", "Cellular communication with daily test signals", "No phone lines to cut"]}],
     "ticks": ["Addressable panels that report the exact device and room", "Smoke, heat, duct, pull station and sprinkler monitoring", "Cellular communication with daily tests", "Battery backup through power outages"],
     "specs": ["Addressable", "Central station", "Cellular"], "note": "We design for what your building needs and nothing it does not. You should not pay for devices that add cost without adding protection."},
    {"id": "surveillance", "anchor": "services", "cat": "Surveillance", "title": "Commercial Surveillance", "img": "cameras",
     "alt": "Rows of white security cameras mounted on a dark wall",
     "text": "We walk the site with you and place every camera for a reason, discreet or deliberately visible. Businesses with several locations see every site under one login.",
     "cols": [{"h": "Cameras", "items": ["Domes indoors, turrets outdoors", "Bullet cameras for long sight lines", "Pan, tilt and zoom where coverage needs it", "2 MP to 4K, infrared to 30 to 50 m"]},
              {"h": "Analytics", "items": ["Pre- and post-motion recording", "Object removal detection", "License plate recognition", "People counting and line crossing", "SD card backup inside each camera"]}],
     "ticks": ["Site walkthrough and camera placement plan", "2 MP to 4K cameras with infrared night vision", "Multiple sites under one account", "Analytics such as line crossing and plate recognition"],
     "specs": ["Hikvision", "TruVision", "Panasonic", "Advidia"], "note": None},
    {"id": "access", "anchor": "services", "cat": "Access", "title": "Access Control", "img": "office-glass",
     "alt": "A long office corridor lined with glass partitions and doors",
     "text": "Decide who goes where, and when, with a full log of every entry. Our core platform scales from 1 to 64 doors and links to cameras for a photo of each event.",
     "cols": [{"h": "Hardware", "items": ["Magnetic locks and electric strikes", "Card and fob readers", "Request-to-exit buttons and motion sensors", "Steel, wood and glass doors, inside and out"]},
              {"h": "Management", "items": ["App for phone, tablet or computer", "Reports by door, person or time", "Several buildings from one office", "Tie-in with the fire system", "Fobs issued and admins trained"]}],
     "ticks": ["1 to 64 doors on one modular system", "Reports by door, person or time", "A photo with every access event", "Remote management across sites"],
     "specs": ["TruPortal", "TruVision link", "1 to 64 doors"], "note": None},
    {"id": "av", "anchor": "services", "cat": "Audio Video", "title": "Commercial Audio / Video", "img": "conference-city",
     "alt": "A conference room with a timber table and city views",
     "text": "Conference rooms, paging, background music and displays, designed so the people using them never need to call us into the room.",
     "cols": [{"h": "Rooms", "items": ["Projector or large flat panel", "Laptop connection at the table", "Wireless microphones for larger rooms", "In-ceiling speakers mixing voice and computer audio"]},
              {"h": "Building", "items": ["Paging and evacuation announcements", "Background music by zone", "Displays for sports, menus and camera feeds", "Microphones and mixers for gyms and auditoriums"]}],
     "ticks": ["Conference and training rooms anyone can use", "Paging and announcements across a building", "Background music, zoned and app controlled", "A full lesson for your team at handover"],
     "specs": ["Sonos", "Denon HEOS", "BrightSign", "Commercial displays"], "note": "Displays that run most of the day, seven days a week, need to be commercial models. Consumer TVs wear out early, and commercial use usually voids their warranty."},
    {"id": "retail", "anchor": "services", "cat": "Retail", "title": "Professional &amp; Retail", "img": "office-open",
     "alt": "An open office with glass walls and long tables",
     "text": "Reception areas, waiting rooms, treatment rooms and sales floors. Security, cameras, access, music and signage that make the space work for staff and customers.",
     "cols": [{"h": "For customers", "items": ["Background music from your streaming service", "BrightSign signage for menus and offers", "Conference room displays for presentations"]},
              {"h": "For owners", "items": ["Alarm with individual user codes", "Remote camera viewing", "Fob access to restricted rooms", "One walkthrough, one design, one installer"]}],
     "ticks": ["Background music and digital signage", "Alarm with per-user codes", "Remote camera access", "Fob access to restricted areas"],
     "specs": ["Reception", "Waiting rooms", "Retail floors"], "note": None},
    {"id": "integrated", "anchor": "services", "cat": "Integration", "title": "Integrated Building Systems", "img": "server",
     "alt": "Server racks with bundled network cabling",
     "text": "Cameras, access, alarm and AV planned together so they share data. Access events carry a photo, alarms bring up the right camera, and everything is managed from one place.",
     "cols": [{"h": "Integration", "items": ["Camera and access systems linked", "Remote administration across buildings", "Coordination with your IT team, or full networking by us", "Fire system tie-in for door release"]},
              {"h": "Delivery", "items": ["Walkthrough and design", "Cabling, installation and programming", "Training for your administrators", "Service and expansion after handover"]}],
     "ticks": ["Shared data between cameras, doors and alarm", "One place to manage several buildings", "We work with your IT team or handle the network", "Training and service after handover"],
     "specs": ["TruVision", "TruPortal", "Multi-site"], "note": None},
]

COM_SECTORS = [
    {"title": "Schools & education", "tags": "Paging · Access · Fire", "img": "classroom"},
    {"title": "Municipal buildings", "tags": "Access · Surveillance", "img": "campus"},
    {"title": "Medical & dental", "tags": "Security · AV · Access", "img": "dental"},
    {"title": "Country clubs", "tags": "Audio · Cameras · Fire", "img": "hotel-night"},
    {"title": "Restaurants & hospitality", "tags": "Music · Screens · Paging", "img": "restaurant"},
    {"title": "Retail", "tags": "Cameras · Signage · Alarm", "img": "retail"},
    {"title": "Offices", "tags": "Conference AV · Access", "img": "conference"},
]

LOG = [
    ("07:58:12", "Door 01", "Access granted · Staff fob 0418", False),
    ("07:58:13", "Cam 06", "Photo linked to door 01 event", False),
    ("18:45:20", "System", "Armed away · User 03", False),
    ("22:14:09", "Zone 14", "Motion · Room 112 · East wing", True),
    ("22:14:11", "Cam 11", "Live view sent to monitoring", False),
    ("02:00:00", "Comm", "Cellular daily test · OK", False),
]

COMPARE = [
    ("Best for", "Sites with up to 32 cameras", "Large or growing sites, with no practical camera limit"),
    ("Platform", "Embedded recorder with its own operating system and storage", "A Windows server running camera management software"),
    ("Upkeep", "Low. Cost effective and easy to manage", "Higher. The server needs ongoing maintenance"),
    ("Licensing", "No per-camera license fees", "Often per camera, renewed every few years. Panasonic Advidia cameras avoid this"),
    ("Platforms", "Hikvision, TruVision", "Panasonic Video Insight"),
]

COM_FAQ = [
    {"q": "Do you use the same equipment in commercial installs as in homes?",
     "a": "It depends on the situation. Some applications call for commercial grade equipment. A display running most of the day, seven days a week, has to be a commercial model: a consumer TV will not last, and commercial use usually voids its warranty."},
    {"q": "Are all these devices really necessary for my fire system?",
     "a": "Code sets the minimum for your building's size and use, and your local fire official enforces it. We design to that requirement and tell you plainly what is required and what is optional, so you are not paying for devices you do not need."},
    {"q": "How do I bring my fire system up to code?",
     "a": "Start with a survey. We review your existing panel and devices against the current requirements for your building, then set out what needs to change before inspection."},
    {"q": "What happens to access control if we lose power?",
     "a": "Panels and locks keep running on battery backup within its capacity. Beyond that, each door is set to fail safe or fail secure according to its role, so exit paths release while storage and server rooms stay locked."},
]

# ---------------------------------------------------------------- ABOUT
PRINCIPLES = [
    {"title": "Survey first", "text": "Every design starts on site, with the floor plan and how you live or work."},
    {"title": "Proven hardware", "text": "We test new equipment continually and install only what earns its place."},
    {"title": "Installed properly", "text": "Placement, mounting and wiring decide whether a system lasts."},
    {"title": "Built to grow", "text": "Sized for today, with capacity for the technology that comes next."},
    {"title": "One relationship", "text": "You speak to people who know your system and how it went in."},
]

TIMELINE = [
    {"kicker": "Then", "era": "1990s", "img": "facade-detail", "alt": "Warm light behind a dark timber facade",
     "title": "Wired panels and keypads",
     "text": "Hardwired alarm panels, keypads and phone-line dialers. Systems were judged by how well they were installed, and the best of them are still running.",
     "spec": [("Signal", "Copper phone line"), ("Video", "Analog CCTV, tape"), ("Control", "Keypad")]},
    {"kicker": "Then", "era": "2000s", "img": "theater-seats", "alt": "Rows of cinema seats in a dark auditorium",
     "title": "Networks arrive",
     "text": "Broadband brought the first IP cameras and remote viewing. Home theater moved from the den into dedicated rooms with projectors and surround sound.",
     "spec": [("Signal", "Phone and internet"), ("Video", "Early IP, DVR"), ("Control", "Touchscreens")]},
    {"kicker": "Then", "era": "2010s", "img": "smart-lock", "alt": "A phone app controlling a smart lock",
     "title": "Everything on the phone",
     "text": "Smart locks, thermostats and Control4 put the whole house in an app. Copper lines began to disappear, and monitored systems moved to cellular radio.",
     "spec": [("Signal", "Cellular radio"), ("Video", "HD IP, NVR"), ("Control", "Apps and scenes")]},
    {"kicker": "Now", "era": "Today", "img": "server", "alt": "Server racks with bundled network cabling",
     "title": "Integrated by design",
     "text": "4K cameras with analytics, access control that logs a photo with every entry, and one interface for the whole home or building.",
     "spec": [("Signal", "Cellular, tested daily"), ("Video", "Up to 4K, analytics"), ("Control", "One app, keypads, voice")]},
]

ABOUT_SECTORS = [
    {"title": "Private residences", "img": "living-open", "alt": "An open living room with glass walls onto a deck",
     "text": "Security, automation, theater and audio for new builds and established homes."},
    {"title": "Schools & municipal", "img": "campus", "alt": "A brick civic building behind a lawn",
     "text": "Fire, paging, access control and cameras for public buildings."},
    {"title": "Medical & professional", "img": "dental", "alt": "A bright, modern dental treatment room",
     "text": "Reception, treatment and waiting rooms that are secure and comfortable."},
    {"title": "Clubs & hospitality", "img": "hotel-night", "alt": "A resort pool and pavilion lit at night",
     "text": "Music, screens, paging and surveillance across indoor and outdoor spaces."},
]

PROCESS = [
    {"title": "Conversation", "text": "Call or send the form. We talk through the property, your goals and the timing."},
    {"title": "Site survey", "text": "We walk the home or building, measure, and note what already exists."},
    {"title": "Design", "text": "A system design and proposal built from proven components, with clear options."},
    {"title": "Installation", "text": "Our own technicians run cable, mount, terminate and program everything."},
    {"title": "Handover", "text": "A full lesson on your system, and how to expand it later on."},
    {"title": "Service", "text": "Monitoring, maintenance and a number that reaches people who know your install."},
]

# Map towns (lat, lon, label, anchor)
TOWNS = [
    (40.694, -75.190, "Phillipsburg", "end"),
    (40.758, -74.979, "Washington", "start"),
    (40.854, -74.829, "Hackettstown", "start"),
    (41.033, -74.638, "Sparta", "start"),
    (40.637, -74.910, "Clinton", "start"),
    (40.585, -74.960, "Pittstown", "end"),
    (40.512, -74.859, "Flemington", "start"),
    (40.574, -74.610, "Somerville", "start"),
    (40.797, -74.481, "Morristown", "start"),
    (40.357, -74.667, "Princeton", "start"),
    (40.486, -74.452, "New Brunswick", "start"),
    (40.736, -74.172, "Newark", "start"),
    (40.758, -73.986, "Manhattan", "start"),
]
HQ = (40.667, -75.157)
